//===- CJIRVerifier.h - -----------------------------------------*- C++ -*-===//
//
// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.
//
//===----------------------------------------------------------------------===//
//
// This file provides interface to "Cangjie IR Verifier" pass.
//
// This pass will verify whether the IR generated by the frontend of the cangjie
// meets the requirements.
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_TRANSFORMS_SCALAR_CJ_IR_VERIFIER_H
#define LLVM_TRANSFORMS_SCALAR_CJ_IR_VERIFIER_H

#include "llvm/IR/PassManager.h"

namespace llvm {
class Module;

struct CJIRVerifier : public PassInfoMixin<CJIRVerifier> {
  PreservedAnalyses run(Module &M, ModuleAnalysisManager &) const;
};
} // namespace llvm

#endif // LLVM_TRANSFORMS_SCALAR_CJ_IR_VERIFIER_H