; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -cj-rewrite-statepoint -S 2>&1 | FileCheck %s
; RUN: opt < %s -passes=cj-rewrite-statepoint -S 2>&1 | FileCheck %s


@global = external addrspace(1) global i8

; derived %select base null
define i8 @test(i1 %cond) gc "cangjie" {
; CHECK-LABEL: @test(
; CHECK-NEXT:    [[DERIVED1:%.*]] = getelementptr i8, i8 addrspace(1)* @global, i64 1
; CHECK-NEXT:    [[DERIVED2:%.*]] = getelementptr i8, i8 addrspace(1)* @global, i64 2
; CHECK-NEXT:    [[SELECT:%.*]] = select i1 [[COND:%.*]], i8 addrspace(1)* [[DERIVED1]], i8 addrspace(1)* [[DERIVED2]]
; CHECK-NEXT:    [[TOKEN:%.*]] = call token (...) @llvm.cj.gc.statepoint(i64 0, i32 0, void ()* @extern, i32 0, i32 0)
; CHECK-NEXT:    [[LOAD:%.*]] = load i8, i8 addrspace(1)* [[SELECT]], align 1
; CHECK-NEXT:    ret i8 [[LOAD]]
;
  %derived1 = getelementptr i8, i8 addrspace(1)* @global, i64 1
  %derived2 = getelementptr i8, i8 addrspace(1)* @global, i64 2
  %select = select i1 %cond, i8 addrspace(1)* %derived1, i8 addrspace(1)* %derived2
  call void @extern()
  %load = load i8, i8 addrspace(1)* %select
  ret i8 %load
}

declare void @extern() gc "cangjie"
