; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -cj-rewrite-statepoint < %s | FileCheck %s

target triple = "x86_64-unknown-linux-gnu"
target datalayout = "e-ni:1:6"

declare void @foo()

define i8 addrspace(1)* @test(i64 %i) gc "cangjie" {
; CHECK-LABEL: @test(
; CHECK-NEXT:    [[P:%.*]] = inttoptr i64 [[I:%.*]] to i8 addrspace(1)*
; CHECK-NEXT:    [[TOKEN:%.*]] = call token (...) @llvm.cj.gc.statepoint(i64 0, i32 0, void ()* @foo, i32 0, i32 0) [ "gc-live"(i8 addrspace(1)* [[P]]) ]
; CHECK-NEXT:    [[P_RELOC:%.*]] = call coldcc i8 addrspace(1)* @llvm.cj.gc.relocate.p1i8(token [[TOKEN]], i32 0, i32 0)
; CHECK-NEXT:    ret i8 addrspace(1)* [[P_RELOC]]
;
  %p = inttoptr i64 %i to i8 addrspace(1)*
  call void @foo()
  ret i8 addrspace(1)* %p
}
