; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -cj-rewrite-statepoint -S 2>&1 | FileCheck %s
; RUN: opt < %s -passes=cj-rewrite-statepoint -S 2>&1 | FileCheck %s

@global = external addrspace(1) global i8

define i8 @test(i64 %offset) gc "cangjie" {
; CHECK-LABEL: @test(
; CHECK-NEXT:    [[DERIVED:%.*]] = getelementptr i8, i8 addrspace(1)* @global, i64 [[OFFSET:%.*]]
; CHECK-NEXT:    [[TOKEN:%.*]] = call token (...) @llvm.cj.gc.statepoint(i64 0, i32 0, void ()* @extern, i32 0, i32 0)
; CHECK-NEXT:    [[LOAD:%.*]] = load i8, i8 addrspace(1)* [[DERIVED]], align 1
; CHECK-NEXT:    ret i8 [[LOAD]]
;
  %derived = getelementptr i8, i8 addrspace(1)* @global, i64 %offset
  call void @extern()
  %load = load i8, i8 addrspace(1)* %derived
  ret i8 %load
}

declare void @extern() gc "cangjie"
