; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals
; RUN: opt -S -cj-rewrite-statepoint < %s | FileCheck %s
; RUN: opt -S -passes=cj-rewrite-statepoint < %s | FileCheck %s
; Ensure statepoints copy (valid) attributes from callsites.

declare void @f(i8 addrspace(1)* %obj)

; copy over norecurse noimplicitfloat to statepoint call
define void @test1(i8 addrspace(1)* %arg) gc "cangjie" {
; CHECK-LABEL: @test1(
; CHECK-NEXT:    [[TOKEN:%.*]] = call token (...) @llvm.cj.gc.statepoint(i64 0, i32 0, void (i8 addrspace(1)*)* @f, i32 1, i32 0, i8 addrspace(1)* [[ARG:%.*]]) #[[ATTR1:[0-9]+]] [ "gc-live"(i8 addrspace(1)* [[ARG]]) ]
; CHECK-NEXT:    [[ARG_RELOCATED:%.*]] = call coldcc i8 addrspace(1)* @llvm.cj.gc.relocate.p1i8(token [[TOKEN]], i32 0, i32 0)
; CHECK-NEXT:    ret void
;

  call void @f(i8 addrspace(1)* %arg) #1
  ret void
}


attributes #1 = { norecurse noimplicitfloat }
;.
; CHECK: attributes #[[ATTR0:[0-9]+]] = { nounwind readnone }
; CHECK: attributes #[[ATTR1]] = { noimplicitfloat norecurse }
;.
